/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "sli_bt_gattdb_def.h"

extern const sli_bt_gattdb_t gattdb;

#define gattdb_generic_attribute              1
#define gattdb_service_changed_char           3
#define gattdb_database_hash                  6
#define gattdb_client_support_features        8
#define gattdb_device_name                    11
#define gattdb_device_information             14
#define gattdb_manufacturer_name_string       16
#define gattdb_system_id                      18
#define gattdb_weight_scale                   19
#define gattdb_weight_measurement             21
#define gattdb_led                            23
#define gattdb_led_color                      25
#define gattdb_led_frequency                  28
#define gattdb_team                           32
#define gattdb_health_thermometer             34
#define gattdb_temperature_measurement        36
#define gattdb_temperature_type               39
#define gattdb_intermediate_temperature       41
#define gattdb_measurement_interval           44
#define gattdb_valid_range                    46
#define gattdb_ota                            47
#define gattdb_ota_control                    49


#endif // __GATT_DB_H
