/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "sli_bt_gattdb_def.h"

extern const sli_bt_gattdb_t gattdb;

#define gattdb_generic_attribute              1
#define gattdb_service_changed_char           3
#define gattdb_database_hash                  6
#define gattdb_client_support_features        8
#define gattdb_device_name                    11
#define gattdb_device_information             14
#define gattdb_manufacturer_name_string       16
#define gattdb_system_id                      18
#define gattdb_weight_scale                   19
#define gattdb_weight_measurement             21
#define gattdb_scale_offset                   24
#define gattdb_scale_divider                  26
#define gattdb_weight_scale_feature           28
#define gattdb_led                            29
#define gattdb_led_color                      31
#define gattdb_led_frequency                  34
#define gattdb_team                           38
#define gattdb_ota                            40
#define gattdb_ota_control                    42


#endif // __GATT_DB_H
